// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD5oqpb7nviRu_ZCd7UF5Ha71KFCpWmTQ',
    appId: '1:312590696826:web:82316f2a0d19d1909896c3',
    messagingSenderId: '312590696826',
    projectId: 'code2codes-ba5a2',
    authDomain: 'code2codes-ba5a2.firebaseapp.com',
    storageBucket: 'code2codes-ba5a2.firebasestorage.app',
    measurementId: 'G-R02S2KBVXP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7Uaw7Q427bhEVtZhJNaPiXwsNOrWnL5I',
    appId: '1:312590696826:android:669011c60321b8769896c3',
    messagingSenderId: '312590696826',
    projectId: 'code2codes-ba5a2',
    storageBucket: 'code2codes-ba5a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN1bvpsocEQ1scuAxSLfJyEGmGvQnNiag',
    appId: '1:312590696826:ios:fafb0a51b36b9a7c9896c3',
    messagingSenderId: '312590696826',
    projectId: 'code2codes-ba5a2',
    storageBucket: 'code2codes-ba5a2.firebasestorage.app',
    iosBundleId: 'com.example.code2codes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAN1bvpsocEQ1scuAxSLfJyEGmGvQnNiag',
    appId: '1:312590696826:ios:fafb0a51b36b9a7c9896c3',
    messagingSenderId: '312590696826',
    projectId: 'code2codes-ba5a2',
    storageBucket: 'code2codes-ba5a2.firebasestorage.app',
    iosBundleId: 'com.example.code2codes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBD5oqpb7nviRu_ZCd7UF5Ha71KFCpWmTQ',
    appId: '1:312590696826:web:d9827143a27b06689896c3',
    messagingSenderId: '312590696826',
    projectId: 'code2codes-ba5a2',
    authDomain: 'code2codes-ba5a2.firebaseapp.com',
    storageBucket: 'code2codes-ba5a2.firebasestorage.app',
    measurementId: 'G-RQRYVPLD25',
  );
}
